import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // selfHostingSidebar: [{type: 'category', label: 'Test', items: ['test/test']}],
  selfHostingSidebar: [
    {type: 'category', label: 'Self-Hosting', items: [
      'self-hosting/Self-hosting',
      {type: 'category', label: 'Email', items: [
        'self-hosting/Email/self-hosting-mail',
        'self-hosting/Email/self-hosting-mail-solution',
        'self-hosting/Email/self-hosting-mail-requirements',
        'self-hosting/Email/self-hosting-mail-gen-keys', // Step 1
        'self-hosting/Email/self-hosting-mail-aws-infrastructure', // Step 2
        'self-hosting/Email/self-hosting-mail-wireguard', // Step 3
        'self-hosting/Email/self-hosting-mail-containers', // Step 4
        'self-hosting/Email/self-hosting-mail-bind', // Step 5
        'self-hosting/Email/self-hosting-mail-unblock', // Step 6
        'self-hosting/Email/self-hosting-mail-config-stalwart', // Step 7
        'self-hosting/Email/self-hosting-mail-test', // Step 8
      ]},
      // {type: 'category', label: 'Plex', items: [
      // ]},
    ]},
  ],
  interestingTechSidebar: [
    {type: 'doc', label: 'Interesting Tech', id: 'interesting-tech'},
  ],
};

export default sidebars;
