import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // selfHostingSidebar: [{type: 'category', label: 'Test', items: ['test/test']}],
  manualSidebar: [
    // 'self-hosting/Self-hosting',
    // {type: 'category', label: 'Email', items: ['self-hosting/Email/self hosting mail']}
    {type: 'category', label: 'Self-Hosting', items: [
      'self-hosting/Self-hosting',
      // {type: 'autogenerated', dirName: 'self-hosting/Email'},
      {type: 'category', label: 'Email', items: [
        'self-hosting/Email/self-hosting-mail',
        'self-hosting/Email/Solution',
        'self-hosting/Email/Requirements',
        'self-hosting/Email/Step 1 - Generate WireGuard keys',
        'self-hosting/Email/Step 2 - Setup AWS infrastructure',
        'self-hosting/Email/Step 3 - Deploy WireGuard server',
        'self-hosting/Email/Step 4 - Deploy containers for mail and DNS',
        'self-hosting/Email/Step 5 - Configure BIND',
        'self-hosting/Email/Step 6 - Unblock port 25 access',
        'self-hosting/Email/Step 7 - Configure Stalwart',
        'self-hosting/Email/Step 8 - Test sending and receiving',
      ]},
      // {type: 'category', label: 'Plex', items: [
      // ]},
    ]},
  ]

  // selfHostingSidebar: [{type: 'autogenerated', dirName: 'self-hosting'},
  //   {type: 'category', label: 'Email', items: ['self-hosting/Email/self hosting mail']}
  // ],


  // otherSidebar: [{type: 'autogenerated', dirName: 'self-hosting/email'},
  //   {type: 'autogenerated', dirName: 'self-hosting/notemail'}
  // ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
